In [42]:
import pandas as pd
import Bio as bio
from Bio import SeqIO
from Bio import GenBank
import re
import numpy as np

In [67]:
Tax = pd.read_csv('/home/emulciber/MitoClub/mtDnaInvertebrate/Body/2Derived/02_DeriveOfTaxonomyGroups.csv', sep=";")

In [68]:
Tax.head()

,X,RefSeqID,SpeciesNames,Taxonomy,Group1,Group2
0,0,NC_012975.1,Oryzias minutillus,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",Vertebrata,Vertebrata:Actinopterygii
1,1,NC_012976.1,Oryzias dancena,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",Vertebrata,Vertebrata:Actinopterygii
2,2,NC_012979.1,Oryzias luzonensis,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",Vertebrata,Vertebrata:Actinopterygii
3,3,NC_014671.1,Ammothea carolinensis,"[Eukaryota, Metazoa, Ecdysozoa, Arthropoda, Ch...",Ecdysozoa,Ecdysozoa:Chelicerata
4,4,NC_012981.1,Oryzias javanicus,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",Vertebrata,Vertebrata:Actinopterygii

In [69]:
sequences = SeqIO.parse('/home/emulciber/MitoClub/mtDnaInvertebrate/Body/1Raw/mitochondrion.genomic.gbff', "genbank")
for seq_record in sequences:
    try:
        idx = seq_record.id
        Tax.loc[Tax['RefSeqID'] == idx, 'Length'] = len(seq_record.seq)
        Tax.loc[Tax['RefSeqID'] == idx, 'Num_A'] = seq_record.seq.count('A')
        Tax.loc[Tax['RefSeqID'] == idx, 'Num_T'] = seq_record.seq.count('T')
        Tax.loc[Tax['RefSeqID'] == idx, 'Num_G'] = seq_record.seq.count('G')
        Tax.loc[Tax['RefSeqID'] == idx, 'Num_C'] = seq_record.seq.count('C')
    except:
        idx = seq_record.id
        Tax.loc[Tax['RefSeqID'] == idx, 'Length'] = 'NaN'
        Tax.loc[Tax['RefSeqID'] == idx, 'Num_A'] = 'NaN'
        Tax.loc[Tax['RefSeqID'] == idx, 'Num_T'] = 'NaN'
        Tax.loc[Tax['RefSeqID'] == idx, 'Num_G'] = 'NaN'
        Tax.loc[Tax['RefSeqID'] == idx, 'Num_C'] = 'NaN'

/home/emulciber/anaconda3/lib/python3.8/site-packages/Bio/GenBank/Scanner.py:1794: BiopythonParserWarning: Structured comment not parsed for NC_037498. Is it malformed?
  warnings.warn(
/home/emulciber/anaconda3/lib/python3.8/site-packages/Bio/GenBank/Scanner.py:1794: BiopythonParserWarning: Structured comment not parsed for NC_037499. Is it malformed?
  warnings.warn(
/home/emulciber/anaconda3/lib/python3.8/site-packages/Bio/GenBank/Scanner.py:1794: BiopythonParserWarning: Structured comment not parsed for NC_037500. Is it malformed?
  warnings.warn(
/home/emulciber/anaconda3/lib/python3.8/site-packages/Bio/GenBank/Scanner.py:1794: BiopythonParserWarning: Structured comment not parsed for NC_057213. Is it malformed?
  warnings.warn(
/home/emulciber/anaconda3/lib/python3.8/site-packages/Bio/GenBank/Scanner.py:1794: BiopythonParserWarning: Structured comment not parsed for NC_057212. Is it malformed?
  warnings.warn(
/home/emulciber/anaconda3/lib/python3.8/site-packages/Bio/GenBank/Scanner.py:1794: BiopythonParserWarning: Structured comment not parsed for NC_057211. Is it malformed?
  warnings.warn(
/home/emulciber/anaconda3/lib/python3.8/site-packages/Bio/GenBank/Scanner.py:1794: BiopythonParserWarning: Structured comment not parsed for NC_057214. Is it malformed?
  warnings.warn(

In [70]:
Tax.drop(['X'], axis='columns', inplace=True)

In [72]:
Tax = Tax.drop(np.where(Tax['Length'] == 'NaN')[0])

In [73]:
Tax.reset_index(drop=True, inplace=True)

In [74]:
Tax[['Length', 'Num_A', 'Num_T', 'Num_C', 'Num_G']] = Tax[['Length', 'Num_A', 'Num_T', 'Num_C', 'Num_G']].astype('int')

In [75]:
Tax

,RefSeqID,SpeciesNames,Taxonomy,Group1,Group2,Length,Num_A,Num_T,Num_G,Num_C
0,NC_012975.1,Oryzias minutillus,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",Vertebrata,Vertebrata:Actinopterygii,16953,4969,4978,2935,4071
1,NC_012976.1,Oryzias dancena,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",Vertebrata,Vertebrata:Actinopterygii,16863,4888,5168,2778,4029
2,NC_012979.1,Oryzias luzonensis,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",Vertebrata,Vertebrata:Actinopterygii,16666,4403,4556,3103,4604
3,NC_014671.1,Ammothea carolinensis,"[Eukaryota, Metazoa, Ecdysozoa, Arthropoda, Ch...",Ecdysozoa,Ecdysozoa:Chelicerata,15101,6379,5767,1121,1834
4,NC_012981.1,Oryzias javanicus,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",Vertebrata,Vertebrata:Actinopterygii,16892,4523,4616,3004,4749
...,...,...,...,...,...,...,...,...,...,...
12083,NC_022255.1,Microchloropsis salina,"[Eukaryota, Sar, Stramenopiles, Ochrophyta, Eu...",Stramenopiles,Stramenopiles,41907,13544,15200,7101,6062
12084,NC_022256.1,Nannochloropsis limnetica,"[Eukaryota, Sar, Stramenopiles, Ochrophyta, Eu...",Stramenopiles,Stramenopiles,38543,12361,13966,6562,5654
12085,NC_022257.1,Nannochloropsis oculata,"[Eukaryota, Sar, Stramenopiles, Ochrophyta, Eu...",Stramenopiles,Stramenopiles,38444,12361,13880,6566,5637
12086,NC_013704.1,Tanakia koreensis,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",Vertebrata,Vertebrata:Actinopterygii,16563,4669,4372,3002,4520
12087,NC_013705.1,Acheilognathus intermedia,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",Vertebrata,Vertebrata:Actinopterygii,16610,4726,4315,2910,4659

In [76]:
Tax['PrA'] = 100 * Tax['Num_A'] / Tax['Length']
Tax['PrT'] = 100 * Tax['Num_T'] / Tax['Length']
Tax['PrG'] = 100 * Tax['Num_G'] / Tax['Length']
Tax['PrC'] = 100 * Tax['Num_C'] / Tax['Length']

In [77]:
Tax['GC'] = Tax['PrG'] + Tax['PrC']

In [78]:
Tax.to_csv('/home/emulciber/MitoClub/mtDnaInvertebrate/Body/2Derived/03_AddGenomeParameters.csv', sep=";")