In [2]:
import pandas as pd

In [4]:
import Bio as bio
from Bio import SeqIO

In [121]:
d = pd.Series(index=range(1,1001))
bac = pd.DataFrame(d)

<ipython-input-121-8ca214e69e8a>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  d = pd.Series(index=range(1,1001))

In [122]:
bac.head()

    0
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN

In [123]:
bac.loc[0:100, 'HumanGeneAnalog'] = 'ATP6'

In [124]:
bac.loc[0:100, 'GeneName'] = [seq_record.description.split(maxsplit=1)[1] for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\ATP6.txt", "fasta")]

In [125]:
AA = list('ARNDCQEGHILKMFPSTWYV')

In [126]:
for i in AA:
    bac[i] = 0

In [127]:
for a in AA:
    bac.loc[0:100, a] = [seq_record.seq.count(a) for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\ATP6.txt", "fasta")]

In [128]:
bac.loc[101:200, 'HumanGeneAnalog'] = 'COX1'
bac.loc[101:200, 'GeneName'] = [seq_record.description.split(maxsplit=1)[1] for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\COX1.txt", "fasta")]
for a in AA:
    bac.loc[101:200, a] = [seq_record.seq.count(a) for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\COX1.txt", "fasta")]

In [129]:
bac.loc[201:300, 'HumanGeneAnalog'] = 'COX2'
bac.loc[201:300, 'GeneName'] = [seq_record.description.split(maxsplit=1)[1] for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\COX2.txt", "fasta")]
for a in AA:
    bac.loc[201:300, a] = [seq_record.seq.count(a) for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\COX2.txt", "fasta")]

In [130]:
bac.loc[301:400, 'HumanGeneAnalog'] = 'COX3'
bac.loc[301:400, 'GeneName'] = [seq_record.description.split(maxsplit=1)[1] for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\COX3.txt", "fasta")]
for a in AA:
    bac.loc[301:400, a] = [seq_record.seq.count(a) for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\COX3.txt", "fasta")]

In [131]:
bac.loc[401:500, 'HumanGeneAnalog'] = 'CYTB'
bac.loc[401:500, 'GeneName'] = [seq_record.description.split(maxsplit=1)[1] for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\CYTB.txt", "fasta")]
for a in AA:
    bac.loc[401:500, a] = [seq_record.seq.count(a) for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\CYTB.txt", "fasta")]

In [132]:
bac.loc[501:600, 'HumanGeneAnalog'] = 'ND1'
bac.loc[501:600, 'GeneName'] = [seq_record.description.split(maxsplit=1)[1] for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\ND1.txt", "fasta")]
for a in AA:
    bac.loc[501:600, a] = [seq_record.seq.count(a) for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\ND1.txt", "fasta")]

In [133]:
bac.loc[601:700, 'HumanGeneAnalog'] = 'ND2'
bac.loc[601:700, 'GeneName'] = [seq_record.description.split(maxsplit=1)[1] for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\ND2.txt", "fasta")]
for a in AA:
    bac.loc[601:700, a] = [seq_record.seq.count(a) for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\ND2.txt", "fasta")]

In [134]:
bac.loc[701:800, 'HumanGeneAnalog'] = 'ND3'
bac.loc[701:800, 'GeneName'] = [seq_record.description.split(maxsplit=1)[1] for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\ND3.txt", "fasta")]
for a in AA:
    bac.loc[701:800, a] = [seq_record.seq.count(a) for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\ND3.txt", "fasta")]

In [135]:
bac.loc[801:900, 'HumanGeneAnalog'] = 'ND4'
bac.loc[801:900, 'GeneName'] = [seq_record.description.split(maxsplit=1)[1] for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\ND4.txt", "fasta")]
for a in AA:
    bac.loc[801:900, a] = [seq_record.seq.count(a) for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\ND4.txt", "fasta")]

In [136]:
bac.loc[901:1000, 'HumanGeneAnalog'] = 'ND5'
bac.loc[901:1000, 'GeneName'] = [seq_record.description.split(maxsplit=1)[1] for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\ND5.txt", "fasta")]
for a in AA:
    bac.loc[901:1000, a] = [seq_record.seq.count(a) for seq_record in SeqIO.parse(r"C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\ND5.txt", "fasta")]

In [140]:
bac

,HumanGeneAnalog,GeneName,Ala,Arg,Asn,Asp,Cys,Gln,Glu,Gly,...,Leu,Lys,Met,Phe,Pro,Ser,Thr,Trp,Tyr,Val
1,ATP6,MULTISPECIES: F0F1 ATP synthase subunit A [Pro...,11,2,4,1,0,3,2,4,...,23,2,1,4,6,6,12,0,2,5
2,ATP6,F0F1 ATP synthase subunit A [Bradyrhizobium ca...,15,3,5,0,0,5,4,6,...,40,0,2,7,10,3,16,1,3,11
3,ATP6,F0F1 ATP synthase subunit A [Bradyrhizobium ca...,16,3,5,0,0,5,4,6,...,40,0,2,7,10,3,16,1,3,10
4,ATP6,"F0F1 ATP synthase subunit A, partial [Bradyrhi...",15,3,4,0,0,5,4,5,...,33,0,1,6,10,3,15,1,3,10
5,ATP6,F0F1 ATP synthase subunit A [Sandarakinorhabdu...,22,8,6,3,1,2,6,16,...,32,2,7,21,10,7,8,0,5,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,ND5,NADH-quinone oxidoreductase subunit L [Rhodosp...,54,9,10,14,4,6,14,41,...,56,15,22,40,11,36,29,12,16,42
997,ND5,NADH-quinone oxidoreductase subunit L [Candida...,38,6,17,13,3,5,7,34,...,47,16,17,43,13,34,27,7,17,34
998,ND5,NADH-quinone oxidoreductase subunit L [Crenalk...,60,9,5,12,4,7,13,34,...,48,8,21,37,13,22,23,9,17,36
999,ND5,NADH:ubiquinone oxidoreductase subunit L [Stel...,59,12,5,12,3,9,9,35,...,43,7,24,41,13,26,25,10,13,37
1000,ND5,NADH-quinone oxidoreductase subunit L [Rhodosp...,52,14,7,14,3,6,16,35,...,54,9,19,41,12,31,23,8,16,43

In [139]:
bac.drop([0], axis='columns', inplace=True)
bac.columns = ['HumanGeneAnalog','GeneName','Ala','Arg','Asn','Asp','Cys','Gln','Glu','Gly','His','Ile','Leu','Lys','Met','Phe','Pro','Ser','Thr','Trp','Tyr','Val']

In [143]:
bac.to_csv(r'C:\Users\aaren\OneDrive\Рабочий стол\bac_genes\AminoAcidsFromBacteria.csv', sep=';')